POST http://localhost:7711/cxm/api/v2/mfb_sw_l2/props-update/mfb_sw_l2_panels_masked_cut
Content-Type: application/json

{
  "uuids": [ "mfb_sw_panel_66_0_1",
  "mfb_sw_panel_66_0_2",
  "mfb_sw_panel_66_1_1",
  "mfb_sw_panel_66_1_2",
  "mfb_sw_panel_66_2_1",
  "mfb_sw_panel_66_2_2",
  "mfb_sw_panel_66_3_1",
  "mfb_sw_panel_66_3_2",
  "mfb_sw_panel_66_4_1",
  "mfb_sw_panel_66_4_2",
  "mfb_sw_panel_66_5_1",
  "mfb_sw_panel_66_5_2",
  "mfb_sw_panel_66_6_1",
  "mfb_sw_panel_66_6_2",
  "mfb_sw_panel_66_7_1",
  "mfb_sw_panel_66_7_2",
  "mfb_sw_panel_66_8_1",
  "mfb_sw_panel_66_8_2",
  "mfb_sw_panel_66_9_1",
  "mfb_sw_panel_66_9_2",
  "mfb_sw_panel_66_10_1",
  "mfb_sw_panel_66_10_2",
  "mfb_sw_panel_66_11_1",
  "mfb_sw_panel_66_11_2",
  "mfb_sw_panel_66_12_1",
  "mfb_sw_panel_66_12_2",
  "mfb_sw_panel_66_13_1",
  "mfb_sw_panel_66_13_2",
  "mfb_sw_panel_66_14_1",
  "mfb_sw_panel_66_14_2",
  "mfb_sw_panel_66_15_1",
  "mfb_sw_panel_66_15_2",
  "mfb_sw_panel_66_16_1",
  "mfb_sw_panel_66_16_2",
  "mfb_sw_panel_66_17_1",
  "mfb_sw_panel_66_17_2",
  "mfb_sw_panel_66_18_1",
  "mfb_sw_panel_66_18_2",
  "mfb_sw_panel_66_19_1",
  "mfb_sw_panel_66_19_2",
  "mfb_sw_panel_66_20_1",
  "mfb_sw_panel_66_20_2",
  "mfb_sw_panel_66_21_1",
  "mfb_sw_panel_66_21_2",
  "mfb_sw_panel_66_22_1",
  "mfb_sw_panel_66_22_2",
  "mfb_sw_panel_66_23_1",
  "mfb_sw_panel_66_23_2",
  "mfb_sw_panel_66_24_1",
  "mfb_sw_panel_66_24_2",
  "mfb_sw_panel_66_25_1",
  "mfb_sw_panel_66_25_2",
  "mfb_sw_panel_66_26_1",
  "mfb_sw_panel_66_26_2",
  "mfb_sw_panel_66_27_1",
  "mfb_sw_panel_66_27_2",
  "mfb_sw_panel_66_28_1",
  "mfb_sw_panel_66_28_2",
  "mfb_sw_panel_66_29_1",
  "mfb_sw_panel_66_29_2",
  "mfb_sw_panel_66_30_1",
  "mfb_sw_panel_66_30_2",
  "mfb_sw_panel_66_31_1",
  "mfb_sw_panel_66_31_2",
  "mfb_sw_panel_66_32_1",
  "mfb_sw_panel_66_32_2",
  "mfb_sw_panel_66_33_1",
  "mfb_sw_panel_66_33_2",
  "mfb_sw_panel_66_34_1",
  "mfb_sw_panel_66_34_2",
  "mfb_sw_panel_66_35_1",
  "mfb_sw_panel_66_35_2",
  "mfb_sw_panel_66_36_1",
  "mfb_sw_panel_66_36_2",
  "mfb_sw_panel_66_37_1",
  "mfb_sw_panel_66_37_2",
  "mfb_sw_panel_66_38_1",
  "mfb_sw_panel_66_38_2",
  "mfb_sw_panel_66_39_1",
  "mfb_sw_panel_66_39_2",
  "mfb_sw_panel_66_40_1",
  "mfb_sw_panel_66_40_2",
  "mfb_sw_panel_66_41_1",
  "mfb_sw_panel_66_41_2",
  "mfb_sw_panel_66_42_1",
  "mfb_sw_panel_66_42_2",
  "mfb_sw_panel_66_43_1",
  "mfb_sw_panel_66_43_2",
  "mfb_sw_panel_66_44_1",
  "mfb_sw_panel_66_44_2",
  "mfb_sw_panel_66_45_1",
  "mfb_sw_panel_66_45_2",
  "mfb_sw_panel_66_46_1",
  "mfb_sw_panel_66_46_2", "mfb_sw_panel_66_0_1",
  "mfb_sw_panel_66_0_2",
  "mfb_sw_panel_66_1_1",
  "mfb_sw_panel_66_1_2",
  "mfb_sw_panel_66_2_1",
  "mfb_sw_panel_66_2_2",
  "mfb_sw_panel_66_3_1",
  "mfb_sw_panel_66_3_2",
  "mfb_sw_panel_66_4_1",
  "mfb_sw_panel_66_4_2",
  "mfb_sw_panel_66_5_1",
  "mfb_sw_panel_66_5_2",
  "mfb_sw_panel_66_6_1",
  "mfb_sw_panel_66_6_2",
  "mfb_sw_panel_66_7_1",
  "mfb_sw_panel_66_7_2",
  "mfb_sw_panel_66_8_1",
  "mfb_sw_panel_66_8_2",
  "mfb_sw_panel_66_9_1",
  "mfb_sw_panel_66_9_2",
  "mfb_sw_panel_66_10_1",
  "mfb_sw_panel_66_10_2",
  "mfb_sw_panel_66_11_1",
  "mfb_sw_panel_66_11_2",
  "mfb_sw_panel_66_12_1",
  "mfb_sw_panel_66_12_2",
  "mfb_sw_panel_66_13_1",
  "mfb_sw_panel_66_13_2",
  "mfb_sw_panel_66_14_1",
  "mfb_sw_panel_66_14_2",
  "mfb_sw_panel_66_15_1",
  "mfb_sw_panel_66_15_2",
  "mfb_sw_panel_66_16_1",
  "mfb_sw_panel_66_16_2",
  "mfb_sw_panel_66_17_1",
  "mfb_sw_panel_66_17_2",
  "mfb_sw_panel_66_18_1",
  "mfb_sw_panel_66_18_2",
  "mfb_sw_panel_66_19_1",
  "mfb_sw_panel_66_19_2",
  "mfb_sw_panel_66_20_1",
  "mfb_sw_panel_66_20_2",
  "mfb_sw_panel_66_21_1",
  "mfb_sw_panel_66_21_2",
  "mfb_sw_panel_66_22_1",
  "mfb_sw_panel_66_22_2",
  "mfb_sw_panel_66_23_1",
  "mfb_sw_panel_66_23_2",
  "mfb_sw_panel_66_24_1",
  "mfb_sw_panel_66_24_2",
  "mfb_sw_panel_66_25_1",
  "mfb_sw_panel_66_25_2",
  "mfb_sw_panel_66_26_1",
  "mfb_sw_panel_66_26_2",
  "mfb_sw_panel_66_27_1",
  "mfb_sw_panel_66_27_2",
  "mfb_sw_panel_66_28_1",
  "mfb_sw_panel_66_28_2",
  "mfb_sw_panel_66_29_1",
  "mfb_sw_panel_66_29_2",
  "mfb_sw_panel_66_30_1",
  "mfb_sw_panel_66_30_2",
  "mfb_sw_panel_66_31_1",
  "mfb_sw_panel_66_31_2",
  "mfb_sw_panel_66_32_1",
  "mfb_sw_panel_66_32_2",
  "mfb_sw_panel_66_33_1",
  "mfb_sw_panel_66_33_2",
  "mfb_sw_panel_66_34_1",
  "mfb_sw_panel_66_34_2",
  "mfb_sw_panel_66_35_1",
  "mfb_sw_panel_66_35_2",
  "mfb_sw_panel_66_36_1",
  "mfb_sw_panel_66_36_2",
  "mfb_sw_panel_66_37_1",
  "mfb_sw_panel_66_37_2",
  "mfb_sw_panel_66_38_1",
  "mfb_sw_pael_66_38_2",
  "mfb_sw_panel_66_39_1",
  "mfb_sw_panel_66_39_2",
  "mfb_sw_panel_66_40_1",
  "mfb_sw_panel_66_40_2",
  "mfb_sw_panel_66_41_1",
  "mfb_sw_panel_66_41_2",
  "mfb_sw_panel_66_42_1",
  "mfb_sw_panel_66_42_2",
  "mfb_sw_panel_66_43_1",
  "mfb_sw_panel_66_43_2",
  "mfb_sw_panel_66_44_1",
  "mfb_sw_panel_66_44_2",
  "mfb_sw_panel_66_45_1",
  "mfb_sw_panel_66_45_2",
  "mfb_sw_panel_66_46_1",
  "mfb_sw_panel_66_46_2"
    
  ],
  "props": {
    "mount": 1,
    "arch_type": "TEST"
  }
}